# Generated by Django 6.0.7 on 2026-08-02 19:36

from django.db import migrations
from django.db import models


def seed_rules(apps, schema_editor) -> None:
    NormalizationRule = apps.get_model("main", "NormalizationRule")
    # Pattern strings copied verbatim from main/services.py, so behavior stays
    # byte-identical when these rules start being applied at import.
    NormalizationRule.objects.create(
        order=10,
        search=r"\s+(?:Euro|Pound\s+Sterl)\s*\d+\.\d+\s+X\s+\d+\.\d+\s+\(EXCHG RTE\)$",
        replace="",
    )
    NormalizationRule.objects.create(
        order=20,
        search=r"\s+\d{2}/\d{2}.*$",
        replace="",
    )


def unseed_rules(apps, schema_editor) -> None:
    NormalizationRule = apps.get_model("main", "NormalizationRule")
    NormalizationRule.objects.filter(
        search__in=[
            r"\s+(?:Euro|Pound\s+Sterl)\s*\d+\.\d+\s+X\s+\d+\.\d+\s+\(EXCHG RTE\)$",
            r"\s+\d{2}/\d{2}.*$",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_merchant_tag_transaction_merchant_merchant_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(max_length=500)),
                ("replace", models.CharField(blank=True, default="", max_length=500)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(seed_rules, unseed_rules),
    ]
