# Generated by Django 6.0.7 on 2026-08-02 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_normalizationrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="normalizationrule",
            options={"ordering": ["order", "pk"]},
        ),
    ]
